#!/bin/sh

# Flags set by user
gLocal=true # mountPoint at "/"?
gKernelUnmodified=true # Skip kernel compile & installation?
gPartition=false
gKernelPartition=false

# Values to search
	# Devices
bootPartition=""
lvmPartition=""
kernelPartition=""
	# Files to mount
mountPoint=""
kernelPoint=""

# Log function
log() {
    local message="$(date '+%Y-%m-%d %H:%M:%S'): $1" 2>/dev/null
    echo "$message" 2>/dev/null
}

# !!! De-construct setup-disks script to permit seperate boot and lvm partitioning
defineMount() {
	# Function behavior & User choice
	log "INFO: Considering existing block devices"
		# Increasing readability
    local disableAlpineInstall=false
    local disableKernelReplacement=false
		# User accepts risks
	local bootSectorChosen=true
	local lvmSectorChosen=true
	local kernelSectorChosen=true
		# User acknowledgement if partition requires formatting
	local bootExist=true
	local lvmExist=true
	local kernelExist=true

	# Initial sanity checks of expected behavior: No duplicate entries, valid partitions, format potential, valid device block, compatibility check, and finally global flag check
		# Duplication Sanity
	if [ "$lvmPartition" = "$bootPartition" ] && [ "$bootPartition" != "" ] && [ "$lvmPartition" != "" ]; then echo "Duplicate conflicting entry with: $bootPartition"; bootSectorChosen=false; lvmSectorChosen=false; kernelSectorChosen=false; bootPartition=""; lvmPartition=""; kernelPartition=""; bootExist=false; lvmExist=false; kernelExist=false; fi
	if [ "$kernelPartition" = "$bootPartition" ] && [ "$bootPartition" != "" ] && [ "$kernelPartition" != "" ]; then echo "Duplicate conflicting entry with: $lvmPartition"; bootSectorChosen=false; lvmSectorChosen=false; kernelSectorChosen=false; bootPartition=""; lvmPartition=""; kernelPartition=""; bootExist=false; lvmExist=false; kernelExist=false; fi
	if [ "$lvmPartition" = "$kernelPartition" ] && [ "$kernelPartition" != "" ] && [ "$lvmPartition" != "" ]; then echo "Duplicate conflicting entry with: $kernelPartition"; bootSectorChosen=false; lvmSectorChosen=false; kernelSectorChosen=false; bootPartition=""; lvmPartition=""; kernelPartition=""; bootExist=false; lvmExist=false; kernelExist=false; fi
    	# Valid partitions & formatting possibility
    if [ ! -z "$(echo $bootPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ] && [ ! -z "$bootPartition" ] && $bootExist; then if [ ! -b "$bootPartition" ] && $gPartition; then echo "Device at $bootPartition partition currently does not exist, will format due to gPartion being specified as $gPartition"; bootExist=false; else echo "Only specified partition with non-existance partition number, and unable to format. Change settings, or specify a different number at the end of: $bootPartition"; bootSectorChosen=false; bootPartition=""; bootExist=false; fi; else if [ ! -z "$bootPartition" ]; then echo "Specified disk without partition number; specify a number at the end of: $bootPartition"; bootSectorChosen=false; bootPartition=""; bootExist=false; fi; fi
    if [ ! -z "$(echo $lvmPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ] && [ ! -z "$lvmPartition" ] && $lvmExist; then if [ ! -b "$lvmPartition" ] && $gPartition; then echo "Device at $lvmPartition partition currently does not exist, will format due to gPartion being specified as $gPartition"; lvmExist=false; else echo "Only specified partition with non-existance partition number, and unable to format. Change settings, or specify a different number at the end of: $lvmPartition"; lvmSectorChosen=false; lvmPartition=""; lvmExist=false; fi; else if [ ! -z "$lvmPartition" ]; then echo "Specified disk without partition number; specify a number at the end of: $lvmPartition"; lvmSectorChosen=false; lvmPartition=""; lvmExist=false; fi; fi
    if [ ! -z "$(echo $kernelPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ] && [ ! -z "$kernelPartition" ] && $kernelExist; then if [ ! -b "$kernelPartition" ] && $gKernelPartition; then echo "Device at $kernelPartition partition currently does not exist, will format due to gPartion being specified as $gPartition"; kernelExist=false; else echo "Only specified partition with non-existance partition number, and unable to format. Change settings, or specify a different number at the end of: $kernelPartition"; kernelSectorChosen=false; kernelPartition=""; kernelExist=false; fi; else if [ ! -z "$kernelPartition" ]; then echo "Specified disk without partition number; specify a number at the end of: $kernelPartition"; kernelSectorChosen=false; kernelPartition=""; kernelExist=false; fi; fi
    	# Valid device block
	if [ ! -b "$bootPartition" ] && $bootExist; then bootPartition=""; lvmPartition=""; bootSectorChosen=false; lvmSectorChosen=false; bootExist=false; lvmExist=false; fi
	if [ ! -b "$lvmPartition" ] && $lvmExist; then bootPartition=""; lvmPartition=""; bootSectorChosen=false; lvmSectorChosen=false; bootExist=false; lvmExist=false; fi
	if [ ! -b "$kernelPartition" ] && $kernelExist; then kernelSectorChosen=false; kernelExist=false; fi
    	# Check with global flags
    if $gLocal; then disableAlpineInstall=true; gPartition=false; bootSectorChosen=true; lvmSectorChosen=true; bootExist=false; lvmExist=false; bootPartition="[self]"; lvmPartition="[self]"; mountPoint="/"; fi # Local installation prohibits: drive partitioning & alpine setup-disk installation
    if $gKernelUnmodified; then disableKernelReplacement=true; gKernelPartition=false; kernelSectorChosen=true; kernelExist=false; kernelPartition="[nowhere]"; kernelPoint=""; fi # If not considering kernel; then skip all kernel functions, formatting, and mounting
	
	# Display list of devices, and consider each of the three important mount & format locations: boot, lvm, and kernel.
	local devBlockSize=1024 # /proc/partitions shows size in 1024-byte blocks; https://unix.stackexchange.com/questions/512945/what-units-are-the-values-in-proc-partitions-and-sys-dev-block-block-size
	local devName=""
	local devBlock=""
	local devLabel=""
	local blockList="\?"
	while ! $disableAlpineInstall || ! $disableKernelReplacement; do
		# Show devices list with size and possible label included
	    local showAgain=false
		echo -e "Device     \tSize     \tLabel (if it exists)\n"
		cat /proc/partitions | grep -ivE ram\|loop\|major\|$blockList\|dm\- | while read -r statLine; do
			if [ "$statLine" = '' ]; then continue; fi
            devName="$(echo $statLine | awk -F ' {1,}' '{print($4)}')"
           	devBlock="$(echo $statLine | awk -F ' {1,}' '{print($3)}')"
            devBlock="$(awk "BEGIN {if ((($devBlock*$devBlockSize)/1073741824) > 1) {print (($devBlock*$devBlockSize)/1073741824) \" GB\"} else {print (($devBlock*$devBlockSize)/1048576) \" MB\"}}")"
            devLabel="$(ls -l /dev/disk/by-label/ | grep -w $devName)"
            echo -e "$devName     \t$devBlock     \t$devLabel"
        done
        
        # Determine location of boot sector, and consider requests that are yet to be formatted
        while ! $disableAlpineInstall && ! $bootSectorChosen && ! $showAgain; do
            if [ -z "$bootPartition" ]; then read -p "From the list above. Specify destination for boot partition [Type 'a' to abort, or 'l' to show list]: " bootPartition; fi
            bootPartition="/dev/$(echo $bootPartition | grep -Eo [^\/]*$)" # Append /dev/
            case $bootPartition in
                /dev/a ) exit;;
                /dev/A ) exit;;
                /dev/l ) showAgain=true; bootPartition=""; continue;;
                /dev/L ) showAgain=true; bootPartition=""; continue;;
                *)
                	if [ "$bootPartition" = "$lvmPartition" ] || [ "$bootPartition" = "$kernelPartition" ]; then echo "Duplicate conflicting entry with: $bootPartition"; showAgain=true; bootPartition=""; continue; fi # Ensure that $kernelPartition is different from the rest
                	# Test if valid device, and then test if partition is a partion and not the full entire device
                	if [ -b "$bootPartition" ]; 
                		then if [ ! -z "$(echo $bootPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then bootSectorChosen=true; bootExist=true; blockList="$blockList|$(echo $bootPartition | grep -Eo [^\/]*$)"; else echo "Only specified disk without partition number. Please specify a number at the end of: $bootPartition"; bootPartition=""; continue; fi
                		else if [ ! -z "$(echo $bootPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ] && $gPartition; then echo "Device at $bootPartition partition currently does not exist, will format due to gPartion being specified as $gPartition"; bootSectorChosen=true; bootExist=false; blockList="$blockList|$(echo $bootPartition | grep -Eo [^\/]*$)"; else echo "Either didn't provide a valid partition that cannot be made with gPartion disabled, or only specified disk without partition number"; bootPartition=""; fi
                	fi
                	;;
            esac
        done
        
        # Determine location of lvm sector, and consider requests that are yet to be formatted
        while ! $disableAlpineInstall && ! $lvmSectorChosen && ! $showAgain; do
            if [ -z "$lvmPartition" ]; then read -p "From the list above. Specify destination for lvm partition [Type 'a' to abort, or 'l' to show list]: " lvmPartition; fi
            lvmPartition="/dev/$(echo $lvmPartition | grep -Eo [^\/]*$)" # Append /dev/
            case $lvmPartition in
                /dev/a ) exit;;
                /dev/A ) exit;;
                /dev/l ) showAgain=true; lvmPartition=""; continue;;
                /dev/L ) showAgain=true; lvmPartition=""; continue;;
                *)
                	if [ "$lvmPartition" = "$bootPartition" ] || [ "$lvmPartition" = "$kernelPartition" ]; then echo "Duplicate conflicting entry with: $lvmPartition"; showAgain=true; lvmPartition=""; continue; fi # Ensure that $kernelPartition is different from the rest
                	# Test if valid device, and then test if partition is a partion and not the full entire device
                	if [ -b "$lvmPartition" ]; 
                		then if [ ! -z "$(echo $lvmPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then lvmSectorChosen=true; lvmExist=true; blockList="$blockList|$(echo $lvmPartition | grep -Eo [^\/]*$)"; else echo "Only specified disk without partition number. Please specify a number at the end of: $lvmPartition"; lvmPartition=""; continue; fi
                		else if [ ! -z "$(echo $lvmPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ] && $gPartition; then echo "Device at $lvmPartition partition currently does not exist, will format due to gPartion being specified as $gPartition"; lvmSectorChosen=true; lvmExist=false; blockList="$blockList|$(echo $lvmPartition | grep -Eo [^\/]*$)"; else echo "Either didn't provide a valid partition that cannot be made with gPartion disabled, or only specified disk without partition number"; lvmPartition=""; fi
                	fi
                	;;
            esac
        done
        
        # Determine location of kernel sector, and consider requests that are yet to be formatted
        while ! $disableKernelReplacement && ! $kernelSectorChosen && ! $showAgain; do
            if [ -z "$kernelPartition" ]; then read -p "From the list above. Specify destination for kernel partition [Type 'a' to abort, or 'l' to show list]: " kernelPartition; fi
            kernelPartition="/dev/$(echo $kernelPartition | grep -Eo [^\/]*$)" # Append /dev/
            case $kernelPartition in
                /dev/a ) exit;;
                /dev/A ) exit;;
                /dev/l ) showAgain=true; kernelPartition=""; continue;;
                /dev/L ) showAgain=true; kernelPartition=""; continue;;
                *)
                	if [ "$kernelPartition" = "$bootPartition" ] || [ "$kernelPartition" = "$lvmPartition" ]; then echo "Duplicate conflicting entry with: $kernelPartition"; showAgain=true; kernelPartition=""; continue; fi # Ensure that $kernelPartition is different from the rest
                	# Test if valid device, and then test if partition is a partion and not the full entire device
                	if [ -b "$kernelPartition" ]; 
                		then if [ ! -z "$(echo $kernelPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then kernelSectorChosen=true; kernelExist=true; blockList="$blockList|$(echo $kernelPartition | grep -Eo [^\/]*$)"; else echo "Only specified disk without partition number. Please specify a number at the end of: $kernelPartition"; kernelPartition=""; continue; fi
                		else if [ ! -z "$(echo $kernelPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ] && $gKernelPartition; then echo "Device at $kernelPartition partition currently does not exist, will format due to gKernelPartition being specified as $gKernelPartition"; kernelSectorChosen=true; kernelExist=false; blockList="$blockList|$(echo $kernelPartition | grep -Eo [^\/]*$)"; else echo "Either didn't provide a valid partition that cannot be made with gPartion disabled, or only specified disk without partition number"; kernelPartition=""; fi
                	fi
                	;;
            esac
        done
        
        # Final sanity check; due to missing compatibility
        if ! $bootExist && $lvmExist; then echo "This script currently does not support a missing boot partition with a valid lvm partition"; blockList="\?"; bootSectorChosen=false; lvmSectorChosen=false; bootExist=false; lvmExist=false; bootPartition=""; lvmPartition=""; fi
        if $bootExist && ! $lvmExist; then echo "This script currently does not support a valid boot partition with a missing lvm partition"; blockList="\?"; bootSectorChosen=false; lvmSectorChosen=false; bootExist=false; lvmExist=false; bootPartition=""; lvmPartition=""; fi
        
        # Break loop
        if $bootSectorChosen && $lvmSectorChosen && $kernelSectorChosen; then break; fi
	done
	log "INFO: Boot partition at $bootPartition; does it currently exist? $bootExist, formatting enabled? $gPartition"
	log "INFO: Lvm partition at $lvmPartition; does it currently exist? $lvmExist, formatting enabled? $gPartition"
	log "INFO: Kernel partition at $kernelPartition; does it currently exist? $kernelExist, formatting enabled? $gKernelPartition"

	log "INFO: Considering where to mount root directory and possible kernel device"
	
#	mountPoint kernelPoint
	while ! $disableAlpineInstall; do
		break
	done
	
	while ! $disableKernelReplacement; do
		break
	done

	log "INFO: User formatting, partitioning, and mounting are processed"

	# Alpine installation
#    log "INFO: Checking if this is a fresh installation"
	
#    log "INFO: Started formatting Alpine disk!"
	
#	log "INFO: Mounting all Alpine partitions"
	
#	log "INFO: Checking if Alpine is installed"
	
#	log "INFO: Installing Alpine on disk"


	# Kernel secondary disk installation
#   log "INFO: Checking if kernel already exists"
    
#    log "INFO: Started formatting Kernel disk!"
	
#	log "INFO: Mounting kernel partitions in home directory"
	
#	log "INFO: Checking if kernel is latest version or higher from secondary disk"
	
#	log "INFO: Installing Kernel on secondary disk"
		
# 	log "INFO: Finish preparing block devices"
}

# Test case: All valid paths
gLocal=false
gKernelUnmodified=false
gPartition=true
gKernelPartition=true

bootPartition=""
lvmPartition=""
kernelPartition=""
defineMount
