#!/bin/sh

# Flags set by user
gLocal=true # mountPoint at "/"? Otherwise in /mnt
gKernelUnmodified=true # Skip kernel mounting & replacement? Otherwise in $mountPoint/home/$buildUsername
gPartition=false # Intention to reset or create new partitions of Alpine disk
gKernelPartition=false # Intention to reset or create new partitions of Kernel disk storage
partitionSector="6144" # Leave this as 2048, as it determines which sector on the device to use. Leave it alone, unless you know what you are doing
kernelPartitionSector="2048" # USED IF IT IS A NEW DISK. Leave this as 2048, as it determines which sector on the device to use. Leave it alone, unless you know what you are doing
# Must include units: "B", "kB", "MB", "KiB", "MiB", "GB", "GiB", "TB", "TiB", "PB", "PiB", "EB", "EiB", or Sectors: "s"
lvmFull=true # Will Alpine installation use entire disk? Or a portion of disk?
kernelFull=true # Will Alpine installation use entire disk? Or a portion of disk?
bootSize="1G"
lvmSize="0G" # Required if lvmFull is set to false
kernelSize="0G" # Required if lvmFull is set to false

# Values to search, or be set by user
	# Devices
bootPartition=""
lvmPartition=""
kernelPartition=""
	# Files to mount
mountPoint=""

# Log function
log() {
    local message="$(date '+%Y-%m-%d %H:%M:%S'): $1" 2>/dev/null
    echo "$message" 2>/dev/null
}

# !!! De-construct setup-disks script to permit seperate boot and lvm partitioning
defineMount() {
	# Function behavior & User choice
	log "INFO: Considering existing block devices"
		# Increasing readability
    local disableAlpineInstall=false
    local disableKernelReplacement=false
		# User accepts risks
	local bootSectorChosen=true
	local lvmSectorChosen=true
	local kernelSectorChosen=true
		# User acknowledgement if partition requires formatting
	local bootExist=true
	local lvmExist=true
	local kernelExist=true
    	# Check with global flags
    if $gLocal; then disableAlpineInstall=true; gPartition=false; bootSectorChosen=true; lvmSectorChosen=true; bootExist=false; lvmExist=false; bootPartition="[self]"; lvmPartition="[self]"; mountPoint="/"; fi # Local installation prohibits: drive partitioning & alpine setup-disk installation
    if $gKernelUnmodified; then disableKernelReplacement=true; gKernelPartition=false; kernelSectorChosen=true; kernelExist=false; kernelPartition="[nowhere]"; kernelPoint=""; fi # If not considering kernel; then skip all kernel functions, formatting, and mounting
	
	# Display list of devices, and consider each of the three important mount & format locations: boot, lvm, and kernel.
	local devBlockSize=1024 # /proc/partitions shows size in 1024-byte blocks; https://unix.stackexchange.com/questions/512945/what-units-are-the-values-in-proc-partitions-and-sys-dev-block-block-size
	local devName=""
	local devBlock=""
	local devLabel=""
	local devType=""
	local blockList="\?"
	local showAgain=false
	while ! $disableAlpineInstall || ! $disableKernelReplacement; do
		# Show devices list with size and possible label included
		if $showAgain; then
			echo -e "Device     \tSize     \tType\tLabel (if it exists)\n"
			cat /proc/partitions | grep -ivE ram\|loop\|major\|$blockList\|dm\- | while read -r statLine; do
				if [ "$statLine" = '' ]; then continue; fi
            	devName="$(echo $statLine | awk -F ' {1,}' '{print($4)}')"
           		devBlock="$(echo $statLine | awk -F ' {1,}' '{print($3)}')"
            	devBlock="$(awk "BEGIN {if ((($devBlock*$devBlockSize)/1073741824) > 1) {print (($devBlock*$devBlockSize)/1073741824) \" GB\"} else {print (($devBlock*$devBlockSize)/1048576) \" MB\"}}")"
            	devType="$(blkid /dev/$devName | awk -F 'TYPE' 'NF>1{sub(/="/,"",$NF);sub(/".*/,"",$NF);print $NF}')"
            	devLabel="$(ls -l /dev/disk/by-label/ | grep -w $devName)"
            	echo -e "$devName     \t$devBlock \t$devType\t$devLabel"
        	done
        fi
        showAgain=false
        
        # Determine location of boot sector, and consider requests that are yet to be formatted
        while ! $disableAlpineInstall && ! $bootSectorChosen && ! $showAgain; do
            read -p "From the list above. Specify destination for boot partition that is vfat [Type 'a' to abort, or 'l' to show list]: " bootPartition
            bootPartition="/dev/$(echo $bootPartition | grep -Eo [^\/]*$)" # Append /dev/
            case $bootPartition in
                /dev/a ) exit;;
                /dev/A ) exit;;
                /dev/l ) showAgain=true; bootPartition=""; continue;;
                /dev/L ) showAgain=true; bootPartition=""; continue;;
                *)
                	# Temporarely pretend the user choose valid options
                	bootSectorChosen=true
                	bootExist=true
                	;;
            esac
        done
        
        # Determine location of lvm sector, and consider requests that are yet to be formatted
        while ! $disableAlpineInstall && ! $lvmSectorChosen && ! $showAgain; do
            read -p "From the list above. Specify destination for lvm partition that is LVM2_member [Type 'a' to abort, or 'l' to show list]: " lvmPartition
            lvmPartition="/dev/$(echo $lvmPartition | grep -Eo [^\/]*$)" # Append /dev/
            case $lvmPartition in
                /dev/a ) exit;;
                /dev/A ) exit;;
                /dev/l ) showAgain=true; lvmPartition=""; continue;;
                /dev/L ) showAgain=true; lvmPartition=""; continue;;
                *)
                	# Temporarely pretend the user choose valid options
                	lvmSectorChosen=true
                	lvmExist=true
                	;;
            esac
        done
        
        # Determine location of kernel sector, and consider requests that are yet to be formatted
        while ! $disableKernelReplacement && ! $kernelSectorChosen && ! $showAgain; do
            read -p "From the list above. Specify destination for kernel partition that is xfs [Type 'a' to abort, or 'l' to show list]: " kernelPartition
            kernelPartition="/dev/$(echo $kernelPartition | grep -Eo [^\/]*$)" # Append /dev/
            case $kernelPartition in
                /dev/a ) exit;;
                /dev/A ) exit;;
                /dev/l ) showAgain=true; kernelPartition=""; continue;;
                /dev/L ) showAgain=true; kernelPartition=""; continue;;
                *)
                	# Temporarely pretend the user choose valid options
                	kernelSectorChosen=true
                	kernelExist=true
                	;;
            esac
        done

		# Possibility to loop back again
        	# Reset blocklist
        blockList="\?" # Reset
        if ! $disableAlpineInstall && [ ! -z "$bootPartition" ] && [ ! -z "$(echo $bootPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then blockList="$blockList|$(echo $bootPartition | grep -Eo [^\/]*$)"; fi
        if ! $disableAlpineInstall && [ ! -z "$lvmPartition" ] && [ ! -z "$(echo $lvmPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then blockList="$blockList|$(echo $lvmPartition | grep -Eo [^\/]*$)"; fi
        if ! $disableKernelReplacement && [ ! -z "$kernelPartition" ] && [ ! -z "$(echo $kernelPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then blockList="$blockList|$(echo $kernelPartition | grep -Eo [^\/]*$)"; fi
        
        # Start beginning of loop check
        	# Emptyness check
        if ! $disableAlpineInstall && [ -z "$bootPartition" ]; then showAgain=true; bootSectorChosen=false; bootExist=false; echo "Empty value for bootPartition"; fi
        if ! $disableAlpineInstall && [ -z "$lvmPartition" ]; then showAgain=true; lvmSectorChosen=false; lvmExist=false; echo "Empty value for lvmPartition"; fi
        if ! $disableKernelReplacement && [ -z "$kernelPartition" ]; then showAgain=true; kernelSectorChosen=false; kernelExist=false; echo "Empty value for kernelPartition"; fi
        if $showAgain; then continue; fi
        
        # Partition tests:
	        # Duplicate entry
		if ! $disableAlpineInstall && [ "$lvmPartition" = "$bootPartition" ] && [ ! -z "$bootPartition" ] && [ ! -z "$lvmPartition" ]; then echo "Duplicate conflicting entry with: $bootPartition. Resetting all options!"; bootSectorChosen=false; lvmSectorChosen=false; kernelSectorChosen=false; bootPartition=""; lvmPartition=""; kernelPartition=""; bootExist=false; lvmExist=false; kernelExist=false; fi
		if ! $disableAlpineInstall && [ "$kernelPartition" = "$bootPartition" ] && [ ! -z "$bootPartition" ] && [ ! -z "$kernelPartition" ]; then echo "Duplicate conflicting entry with: $lvmPartition. Resetting all options!"; bootSectorChosen=false; lvmSectorChosen=false; kernelSectorChosen=false; bootPartition=""; lvmPartition=""; kernelPartition=""; bootExist=false; lvmExist=false; kernelExist=false; fi
		if ! $disableKernelReplacement && [ "$lvmPartition" = "$kernelPartition" ] && [ ! -z "$kernelPartition" ] && [ ! -z "$lvmPartition" ]; then echo "Duplicate conflicting entry with: $kernelPartition. Resetting all options!"; bootSectorChosen=false; lvmSectorChosen=false; kernelSectorChosen=false; bootPartition=""; lvmPartition=""; kernelPartition=""; bootExist=false; lvmExist=false; kernelExist=false; fi
		if ! $bootSectorChosen || ! $lvmSectorChosen || ! $kernelSectorChosen; then continue; fi # Reset
		
	    	# Valid partition scheme
	    if ! $disableAlpineInstall && [ -z "$(echo $bootPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then echo "Partition formatting for $bootPartition is invalid. Please specify a number correctly [either # or p#] at tail end"; bootSectorChosen=false; bootPartition=""; bootExist=false; fi
	    if ! $disableAlpineInstall && [ -z "$(echo $lvmPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then echo "Partition formatting for $lvmPartition is invalid. Please specify a number correctly [either # or p#] at tail end"; lvmSectorChosen=false; lvmPartition=""; lvmExist=false; fi
	    if ! $disableKernelReplacement && [ -z "$(echo $kernelPartition | grep -E -o [^1234567890][^p][1234567890]+$\|p[1234567890]+$)" ]; then echo "Partition formatting for $kernelPartition is invalid. Please specify a number correctly [either # or p#] at tail end"; kernelSectorChosen=false; kernelPartition=""; kernelExist=false; fi
		if ! $bootSectorChosen || ! $lvmSectorChosen || ! $kernelSectorChosen; then continue; fi # Reset
		
	    	# Formatting acknowledgment, and valid block device check
    	if ! $disableAlpineInstall && [ ! -b "$bootPartition" ] && $gPartition; then echo "vfat bootPartition at $bootPartition partition currently does not exist, but will format due to gPartion being specified as $gPartition"; bootExist=false; fi
    	if ! $disableAlpineInstall && [ ! -b "$lvmPartition" ] && $gPartition; then echo "LVM2_member lvmPartition at $lvmPartition partition currently does not exist, but will format due to gPartion being specified as $gPartition"; lvmExist=false; fi
    	if ! $disableKernelReplacement && [ ! -b "$kernelPartition" ] && $gKernelPartition; then echo "kernelPartition at $gKernelPartition partition currently does not exist, but will format due to gKernelPartition being specified as $gKernelPartition"; kernelExist=false; fi
		if [ ! -b "$bootPartition" ] && $bootExist; then echo "vfat bootPartition at $bootPartition partition currently does not exist, and formatting is currently disabled"; bootPartition=""; bootSectorChosen=false; bootExist=false; fi
		if [ ! -b "$lvmPartition" ] && $lvmExist; then echo "LVM2_member lvmPartition at $lvmPartition partition currently does not exist, and formatting is currently disabled"; lvmPartition=""; lvmSectorChosen=false; lvmExist=false; fi
		if [ ! -b "$kernelPartition" ] && $kernelExist; then echo "xfs kernelPartition at $kernelPartition partition currently does not exist, and formatting is currently disabled"; kernelPartition=""; kernelSectorChosen=false; kernelExist=false; fi
		if ! $bootSectorChosen || ! $lvmSectorChosen || ! $kernelSectorChosen; then continue; fi # Reset
		
	        # Are we mounting non-existant devices without formatting?
        if ! $disableAlpineInstall && ! $bootExist && $lvmExist && ! $gPartition; then echo "This script currently does not support a non-existant boot partition with a valid lvm partition. Enable formatting or pick a different partition"; blockList="\?"; bootSectorChosen=false; lvmSectorChosen=false; bootExist=false; lvmExist=false; bootPartition=""; lvmPartition=""; fi
        if ! $disableAlpineInstall && $bootExist && ! $lvmExist && ! $gPartition; then echo "This script currently does not support a valid boot partition with a non-existant lvm partition. Enable formatting or pick a different partition"; blockList="\?"; bootSectorChosen=false; lvmSectorChosen=false; bootExist=false; lvmExist=false; bootPartition=""; lvmPartition=""; fi
        if ! $disableAlpineInstall && ! $bootExist && ! $lvmExist && ! $gPartition; then echo "This script currently does not support a non-existant boot partition with a non-existant lvm partition. Enable formatting or pick a different partition"; blockList="\?"; bootSectorChosen=false; lvmSectorChosen=false; bootExist=false; lvmExist=false; bootPartition=""; lvmPartition=""; fi
		if ! $bootSectorChosen || ! $lvmSectorChosen || ! $kernelSectorChosen; then continue; fi # Reset
        
        	# Final sanity check when formatting is disabled: IS boot vfat?, IS lvm LVM2_member, and IS kernel xfs?
        if ! $disableAlpineInstall && [ "$(blkid $bootPartition | awk -F 'TYPE' 'NF>1{sub(/="/,"",$NF);sub(/".*/,"",$NF);print $NF}')" != "vfat" ] && ! $gPartition; then echo "Partition at $bootPartition is not FAT32/vfat! Enable formatting or pick a different partition"; blockList="\?"; bootPartition=""; bootSectorChosen=false; bootExist=false; fi
        if ! $disableAlpineInstall && [ "$(blkid $lvmPartition | awk -F 'TYPE' 'NF>1{sub(/="/,"",$NF);sub(/".*/,"",$NF);print $NF}')" != "LVM2_member" ] && ! $gPartition; then echo "Partition at $lvmPartition is not LVM2_member! Enable formatting or pick a different partition"; blockList="\?"; lvmPartition=""; lvmSectorChosen=false; lvmExist=false; fi
        if ! $disableKernelReplacement && [ "$(blkid $kernelPartition | awk -F 'TYPE' 'NF>1{sub(/="/,"",$NF);sub(/".*/,"",$NF);print $NF}')" != "xfs" ] && ! $gKernelPartition; then echo "Partition at $kernelPartition is not xfs! Enable formatting or pick a different partition"; blockList="\?"; kernelPartition=""; kernelSectorChosen=false; kernelExist=false; fi
        
        # Break loop if everything is satisfied
        if $bootSectorChosen && $lvmSectorChosen && $kernelSectorChosen; then break; fi
	done
	log "INFO: vfat boot partition at $bootPartition; does it currently exist? $bootExist, erasure enabled? $gPartition"
	log "INFO: LVM2_member lvm partition at $lvmPartition; does it currently exist? $lvmExist, erasure enabled? $gPartition"
	log "INFO: xfs kernel partition at $kernelPartition; does it currently exist? $kernelExist, formatting enabled? $gKernelPartition"

	# Ensure $mountPoint is defined in a directory of /mnt
	log "INFO: Ensuring mountPoint is declared in /mnt directory, and exists"
	while ! $disableAlpineInstall && [ -z $mountPoint ] || [ "$mountPoint" = "/" ] || [ -z "$(echo $mountPoint | grep -E ^/mnt/.+$)" ]; do
		echo "Directory of /mnt: $(ls -lah /mnt)"
		read -p "Invalid mountpoint is declared at: $mountPoint. Type in an existing or new directory name to select where Alpine installation is mounted within /mnt directory [Type 'a' to abort]: " mountPoint
		mountPoint="/mnt/$(echo $mountPoint | grep -Eo [^\/]*$)" # Append /dev/
		case $mountPoint in
            /mnt/a ) exit;;
            /mnt/A ) exit;;
		esac
	done # Create directory
	mkdir -p $mountPoint
	local kernelPoint="/home/$buildUsername"
	
	log "INFO: Calculating if disk size is appropriate"

	local userAction=false
	echo -e "\n\nPlease review the following configurations before proceeding\n"
	echo -e "Boot partition in vfat disk partition location:\t\t\t$bootPartition"
	echo -e "Alpine installation in LVM2_member disk partition location:\t$lvmPartition"
	echo -e "Alpine custom kernel in xfs disk partition location:\t\t$kernelPartition"
	echo -e "\n\tExists?\tErasure\tFull disk?\tSize if not\tSector offset (if applicable)"
	echo -e "Boot:\t$bootExist\t$gPartition\tn/a\t\t$bootSize\t\t$partitionSector"
	echo -e "LVM:\t$lvmExist\t$gPartition\t$lvmFull\t\t$lvmSize\t\t$partitionSector"
	echo -e "Kernel:\t$kernelExist\t$gKernelPartition\t$kernelFull\t\t$kernelSize\t\t$kernelPartitionSector"
	echo -e "\nMounting alpine location: $mountPoint"
	while ! $userAction; do
		read -p "Confirm procedure? [y/n]: " userChoice
		case $userChoice in
			y ) userAction=true;;
            n ) exit;;
		esac
	done
	log "INFO: User formatting, partitioning, and mounting are confirmed"

	# Alpine installation
#    log "INFO: Checking if this is a fresh installation"
	
#    log "INFO: Started formatting Alpine disk!"
	
#	log "INFO: Mounting all Alpine partitions"
	
#	log "INFO: Checking if Alpine is installed"
	
#	log "INFO: Installing Alpine on disk"


	# Kernel secondary disk installation
#   log "INFO: Checking if kernel already exists"
    
#    log "INFO: Started formatting Kernel disk!"
	
#	log "INFO: Mounting kernel partitions in home directory"
	
#	log "INFO: Checking if kernel is latest version or higher from secondary disk"
	
#	log "INFO: Installing Kernel on secondary disk"
		
# 	log "INFO: Finish preparing block devices"
}

# Test case: All valid paths
gLocal=false
gKernelUnmodified=true
gPartition=true
gKernelPartition=true

bootPartition="/dev/sda2"
lvmPartition="/dev/sda"
kernelPartition=""
defineMount
